// Auto-generated by deploy.yml — Chain: Base Sepolia (84532)
export const CONTRACT_ADDRESSES = {
  ratMaze:        "0x039702bEB07743B2014E9d137CE1604D3cddfe7d" as const,
  gameItems:      "0x1906c7aa262896daD160efCaD0273ece675E9763" as const,
  resourceAMM:    "0xC30bdB8AA9604A5d85545190aD4D5278c50c75c5" as const,
  craftingEngine: "0xbb04d8ce31d01D54A4901DB41429Db220bcA4472" as const,
  burrowVault:    "0x7b01162bCA09777B394A005285286C8EE5059fa4" as const,
  gameGovernor:   "0x0000000000000000000000000000000000000000" as const,
};
