[profile.default]
src            = 'contracts'
out            = 'out'
libs           = ['lib']
test           = 'test'
cache_path     = 'cache'
optimizer      = true
optimizer_runs = 200

remappings = [
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
  "@chainlink/contracts/=lib/chainlink/contracts/",
  "forge-std/=lib/forge-std/src/",
]

[profile.fuzz]
fuzz = { runs = 500 }

[profile.invariant]
invariant = { runs = 256, depth = 15 }

[profile.ci]
fuzz      = { runs = 256 }
invariant = { runs = 64, depth = 16 }

[rpc_endpoints]
mainnet = "https://ethereum.publicnode.com"

[etherscan]
mainnet          = { key = "${ETHERSCAN_API_KEY}" }
sepolia          = { key = "${ETHERSCAN_API_KEY}" }
base_sepolia     = { key = "${BASESCAN_API_KEY}",  url = "https://api-sepolia.basescan.org/api" }
arbitrum_sepolia = { key = "${ARBISCAN_API_KEY}",  url = "https://api-sepolia.arbiscan.io/api" }
optimism_sepolia = { key = "${OPSCAN_API_KEY}",    url = "https://api-sepolia-optimism.etherscan.io/api" }
