# update-addresses.ps1
# Run AFTER forge script DeployAll to auto-patch addresses.ts from broadcast logs.
#
# Usage:
#   .\update-addresses.ps1
#
# Requires: the latest broadcast JSON from foundry in broadcast/DeployAll.s.sol/84532/run-latest.json

$broadcastPath = "broadcast\DeployAll.s.sol\84532\run-latest.json"
$addressesPath = "frontend\src\contracts\addresses.ts"

if (-not (Test-Path $broadcastPath)) {
    Write-Error "Broadcast file not found: $broadcastPath"
    Write-Error "Run 'forge script script/DeployAll.s.sol --rpc-url ... --broadcast' first."
    exit 1
}

$json = Get-Content $broadcastPath -Raw | ConvertFrom-Json
$txs  = $json.transactions

function GetAddress($contractName) {
    $tx = $txs | Where-Object { $_.contractName -eq $contractName } | Select-Object -First 1
    if ($tx) { return $tx.contractAddress }
    return $null
}

$gameItems      = GetAddress "GameItems"
$engine         = GetAddress "ERC1967Proxy"   # CraftingEngine proxy
$vault          = GetAddress "BurrowVault"
$maze           = GetAddress "RatMaze"
$factory        = GetAddress "MarketFactory"

# ResourceAMM pool is deployed by factory — grab by contract name
$pool           = ($txs | Where-Object { $_.contractName -eq "ResourceAMM" } | Select-Object -First 1).contractAddress

if (-not ($gameItems -and $engine -and $vault -and $maze -and $pool)) {
    Write-Warning "Some addresses are missing. Check broadcast JSON manually."
    Write-Host "gameItems      = $gameItems"
    Write-Host "craftingEngine = $engine"
    Write-Host "burrowVault    = $vault"
    Write-Host "ratMaze        = $maze"
    Write-Host "resourceAMM    = $pool"
    exit 1
}

$content = @"
// Auto-generated by update-addresses.ps1 — DO NOT EDIT MANUALLY.
// Chain: Base Sepolia (84532)
export const CONTRACT_ADDRESSES = {
  ratMaze:        "$maze"        as const,
  gameItems:      "$gameItems"   as const,
  resourceAMM:    "$pool"        as const,
  craftingEngine: "$engine"      as const,
  burrowVault:    "$vault"       as const,
  gameGovernor:   "0x0000000000000000000000000000000000000000" as const, // deploy separately
};
"@

Set-Content -Path $addressesPath -Value $content -Encoding UTF8
Write-Host ""
Write-Host "✅  addresses.ts updated successfully!" -ForegroundColor Green
Write-Host "   ratMaze        = $maze"
Write-Host "   gameItems      = $gameItems"
Write-Host "   craftingEngine = $engine"
Write-Host "   burrowVault    = $vault"
Write-Host "   resourceAMM    = $pool"
